#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediacms"
name = "MediaCMS"
description.en = "MediaCMS is a modern, fully featured open source video and media CMS. It is developed to meet the needs of modern web platforms for viewing and sharing media. It can be used to build a small to medium video and media portal within minutes."
description.fr = "MediaCMS est un CMS vidéo et média moderne, open source et complet. Il est développé pour répondre aux besoins des plateformes web modernes pour la visualisation et le partage de médias. Il peut être utilisé pour construire un portail vidéo et média de petite à moyenne taille en quelques minutes."

version = "6.0.0~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "AGPL-3.0"
website = "https://mediacms.io/"
demo = "https://demo.mediacms.io/"
admindoc = "https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md"
userdoc = "https://github.com/mediacms-io/mediacms/blob/main/docs/user_docs.md"
code = "https://github.com/mediacms-io/mediacms"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "AMD64"
multi_instance = true

ldap = false
sso = false

disk = "1G"
ram.build = "4G"
ram.runtime = "4G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mediacms"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/mediacms-io/mediacms/archive/refs/tags/v6.0.0.tar.gz"
    sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
    [resources.apt]
    packages = "python3-venv python3-dev virtualenv redis-server postgresql gcc vim unzip imagemagick xz-utils"

    [resources.database]
    type = "postgresql"
